POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "a",
    "password": "a"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json
     
{
    "username": "alex",
    "password": "1234"
}

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImEiLCJpYXQiOjE1OTIxNDY5NjAsImV4cCI6MTU5MjE0NzU2MH0.yfyVTK_qL0iOJBxPB1N9iO6jvdUlviKfcF_rqNfaSic

###
POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdpYW5pIiwicGFzc3dvcmQiOiIkMmIkMTAkZ0g2VnRxNkdBWXFZT3VCZzJyalI3Lm5hWFhZcUlsNmJOdWhiMXVrYzZ0aTNySnRHVjZwLzYiLCJpYXQiOjE1OTE0NTcyODd9.kWX4ovGzipBWUcH8wy5yza6fEiAEGL9V49bXQEP6YFk"
}

###
GET http://localhost:3000/comms/rock/1
Content-Type: application/json

{
    "id": 1
}

###
PUT http://localhost:3000/comms/rock/1
Content-Type: application/json

{
    "id": "1",
            "comms": [
                {
                    "id" : "1",
                    "text": "E bun",
                    "upVotes": "1",
                    "downVotes": "0"
                },
                {
                    "id" : "2",
                    "text": "Nu e bun",
                    "upVotes": "0",
                    "downVotes": "0"
                }
            ]
}

###
POST http://localhost:3000/history
Content-Type: application/json

{
    "name": "Item modificat",
    "id": "1"
}